### ISSUE TITLE
It won't sync playlist or liked songs due to UnicodeEncodeError (I think)

### ISSUE THREAD

**Issue by livingdeadtrue** [timrae/spotify_to_tidal#77] opened 2024-08-30 17:22 UTC
UnicodeEncodeError: 'charmap' codec can't encode characters in position 35-42: character maps to <undefined>

**Comment by T0pii** [comment] 2024-09-06 16:25
Hi, I just had that issue too. It seems using the default system encoding can cause some issues when special characters are encoded (probably japanese song titles?). 
You can force utf-8 encoding by modifying **line 278** in file `src/spotify_to_tidal/sync.py` :
`with open(file_name, "a", encoding="utf-8") as file:`

This may not be the root cause / the best solution, but this quick fix seems to have worked for me. Let me know if that helped you!

**Comment by timrae** [comment] 2024-09-09 08:04
Should be fixed now, thanks @T0pii

**Closed as completed by timrae** 2024-09-09 08:04 UTC
