### ISSUE TITLE
Tidal client error

### ISSUE THREAD

**Issue by dkatch** [timrae/spotify_to_tidal#5] opened 2022-02-02 21:39 UTC
Hi,

When running `sync.py`, after entering the url that I was redirected to, I get this error message:

```
Login failed: {"status":401,"error":"invalid_client","error_description":"Client with token 8SEZWa4J1NVC5U5Y not found","sub_status":1005}
Traceback (most recent call last):
  File "/Users/davidkatchouni/Downloads/spotify_to_tidal-master/sync.py", line 288, in <module>
    tidal_session = open_tidal_session()
  File "/Users/davidkatchouni/Downloads/spotify_to_tidal-master/auth.py", line 40, in open_tidal_session
    login, future = session.login_oauth_simple()
  File "/usr/local/lib/python3.9/site-packages/tidalapi/__init__.py", line 213, in login_oauth_simple
    login, future = self.login_oauth()
  File "/usr/local/lib/python3.9/site-packages/tidalapi/__init__.py", line 226, in login_oauth
    login, future = self._login_with_link()
  File "/usr/local/lib/python3.9/site-packages/tidalapi/__init__.py", line 240, in _login_with_link
    request.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://auth.tidal.com/v1/oauth2/device_authorization
```

**Comment by timrae** [comment] 2022-02-02 22:01
Duplicate of #4

**Closed as completed by timrae** 2022-02-02 22:01 UTC
